# Generated by Django 3.2 on 2025-04-23 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='achievement_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='intensity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='mood_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='perceived_effort',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='variation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='team',
            name='achievement_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last_challenge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='monthly_goal',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(default='General Fitness', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_workout_time',
            field=models.CharField(default='Morning', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team_join_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team_role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='octofit_tracker.user'),
        ),
        migrations.AddField(
            model_name='workout',
            name='current_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
        migrations.AddField(
            model_name='workout',
            name='equipment_needed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='estimated_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='max_participants',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='success_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='target_muscles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='octofit_tracker.team'),
        ),
    ]
